version: "3.9"

services:
  db:
    image: mariadb:10.9
    environment:
      MARIADB_ROOT_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
  
  rails:
    build: .
    depends_on:
      - db
    ports:
      - "3001:3000"
    volumes:
      - .:/app

volumes:
  db-data:
